const HTTP_BAD_REQUEST = 400
const HTTP_UNAUTHORIZED = 401
const HTTP_FORBIDDEN = 403
const HTTP_NOT_FOUND = 404
const HTTP_NOT_ALLOWED = 405
const HTTP_REQUEST_TIMEOUT = 408
const HTTP_REQUEST_ENTITY_TOO_LARGE = 413
const HTTP_UNKNOW_STATUS = 419
const HTTP_DATA_INVALID = 422
const HTTP_TOO_MANY_REQUESTS = 429
const HTTP_SERVER_ERROR = 500
const HTTP_OK = 200

export {
    HTTP_BAD_REQUEST,
    HTTP_DATA_INVALID,
    HTTP_UNAUTHORIZED,
    HTTP_FORBIDDEN,
    HTTP_REQUEST_TIMEOUT,
    HTTP_NOT_FOUND,
    HTTP_NOT_ALLOWED,
    HTTP_REQUEST_ENTITY_TOO_LARGE,
    HTTP_UNKNOW_STATUS,
    HTTP_TOO_MANY_REQUESTS,
    HTTP_SERVER_ERROR,
    HTTP_OK,
}
